redis:
  image: redis:alpine
  ports:
  - '6379'

db:
  image: postgres:9.4
  ports:
  - '5432'

vote:
    command: python app.py
    image: test-vote:latest
    links:
    - redis:redis 
    ports:
      - '5000:80'
      - '5858:5858'

worker:
    command: dotnet Worker.dll
    image: test-work:latest
    links:
    - redis:redis
    - db:db

result:
    command: nodemon --debug server.js
    image: test-result:latest
    links:
    - db:db
    ports:
    - '5001:80'
